### ISSUE TITLE
Desapareceu a capcha

### ISSUE THREAD

**Issue by fabiomsnunes** [fightnight/fightnight-addons#29]
Desapareceu-me a janela a pedir para inserir a capcha mesmo não tendo nos settings a API e não consigo ver nada no hugefiles por exemplo porque crasha por não inserir a capcha

**Comment by fightnight** [comment]
Verifica se está ok na última versão.

**Comment by fabiomsnunes** [comment]
continua igual, estou a ver por exemplo a série the strain E0101 no Kodi, ele começa a processar com a janela a dizer que pode demorar até 2 minutos e crasha

**Comment by fightnight** [comment]
Manda-me o log do kodi após isso acontecer.

**Comment by fabiomsnunes** [comment]
Não me lembrei, já o podia ter mandado...

**Comment by fightnight** [comment]
Estás a usar que versão do kodi? Usas a skin normal?

**Comment by fabiomsnunes** [comment]
kodi 14 skin default

**Comment by haskily** [comment]
boa noite, ja vi que neste post respondes. pq nao responder nos outros tambem? a minha pergunta é simples, penso eu.. ou sabes o motivo ou nao sabes.

**Comment by fightnight** [comment]
Manda-me o log quando crasha sff.

**Comment by fabiomsnunes** [comment]
falta te escaping por causa dos acentos provavelmente.

**Comment by fabiomsnunes** [comment]
23:07:02 T:4488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 2725, in <module>
                                                elif dialogselect == "1": resolver_servidores(url,name,dialogselect=False)
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 974, in resolver_servidores
                                                menu_servidores(titles,ligacao,name,thumbnail,simounao,wturl,listadecomentarios,dialogselect)
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 1000, in menu_servidores
                                                vaiparaoserver(linkescolha,thumbnail,name,simounao,wturl,index,titles)
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 1026, in vaiparaoserver
                                                elif re.search('hugefiles',linkescolha): hugefiles(linkescolha,fic,name,thumbnail,simounao,wturl)
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 1406, in hugefiles
                                                solver = InputWindow(captcha=captcha_img)
                                              File "C:\Users\F�bio\AppData\Roaming\Kodi\addons\plugin.video.wt\default.py", line 488, in __init__
                                                self.img = xbmcgui.ControlImage(xposition,yposition,wposition,hposition,self.cptloc)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by fightnight** [comment]
Segue este tutorial: https://www.youtube.com/watch?v=G5q-LKcP37Y
