### ISSUE TITLE
Kodi TvOs

### ISSUE THREAD

**Issue by pedrofscaetano** [fightnight/fightnight-addons#71]
O Add-on não funciona no Kodi instalado na Apple TV. Alguma forma de resolver?

**Comment by joaomvfsantos** [comment]
Qual a versão do Kodi que tens instalado no tvOS? Se tens a 17 (Krypton) houve alterações na versão do python e pode acontecer que o fightnight ainda não suporte o Krypton. Eu tenho o TV Portuguesa a correr no Kodi (Krypton) na Apple TV sem problema, mas confesso que não experimentei instalar o repositório.

**Comment by pedrofscaetano** [comment]
Tenho também essa. A grande questão é que isto é uma versão alfa em que "1/3" das coisas não funciona. Eu a TV Portuguesa não uso, mas usava o OK Goals que é das melhores coisinhas que há .. e nada! 
Isto tudo para alem de eles nao atualizarem o addon do Copiapop - em que nao consegues ver as "páginas seguintes" dos conteudos dentro das pastas!

Acho que o fightnight está um bocado ao abandono

**Comment by joaomvfsantos** [comment]
No ficheiro default.py do plugin do OKGoals experimenta adicionar o seguinte logo abaixo da primeira linha de import.

```py
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

Não testei, mas isto resolve quase todos os problemas de compatibilidade que tive com outros addons no Krypton.

Referência: http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

**Comment by fightnight** [comment]
Qual é o problema que tens com o okgoals?

**Comment by pedrofscaetano** [comment]
Joaomvfsantos vou exprimentar, visto que há outros addons que também mostram essa incompatibilidade.

Fighnight: O Okgoals nao abre no Kodi na Appltv4, provavelmente pq aindan ao esta adaptado tal como referiu o Joaomvfsantos!
Aproveito para perguntar para quando a correcção da questão de não conseguir se mudar de página no addon do Copiapop,

Cumprimentos

**Comment by fightnight** [comment]
Dá erro de script? Ainda não há previsão. O objectivo é tornar o addon global a minhateca, copiapop etc.

**Comment by joaomvfsantos** [comment]
@fightnight Excerto dos logs de erros

Quando abro o menu "Latest Goals from Portuguese League":
<pre>
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: (u'\xe9',)
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 419, in <module>
    elif mode==7: ligaportuguesa(url)
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 28, in ligaportuguesa
    addDir('[COLOR orange]%s[/COLOR] [COLOR darkorange](%sh%s)[/COLOR][COLOR blue] - [/COLOR][COLOR white]%s[/COLOR] [COLOR yellow]%s - %s[/COLOR] [COLOR white]%s[/COLOR]' % (data,hora1,hora2,equipa1,resultado1,resultado2,equipa2),'http://www.goalsoftheworld.tk/getcontent.php?rand=%s&id_results=%s' % (str(randint(1, 100)),endereco),1,os.path.join(art,'pt.png'),len(conteudos),pasta=False)
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 341, in addDir
    u=sys.argv[0]+"?url="+urllib.quote_plus(url)+"&mode="+str(mode)+"&name="+urllib.quote_plus(name)+"&thumb="+urllib.quote_plus(iconimage)
  File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib.py", line 1308, in quote_plus
  File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib.py", line 1303, in quote
KeyError: (u'\xe9',)
-->End of Python script error report<--
</pre>

Quando entro no menu "Latest Goals" consigo navegar pelos jogos, selecionar um jogo, assim que escolho uma resolução (480p ou 720p por ex.) acontece o seguinte erro:

<pre>
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'module' object has no attribute 'PLAYER_CORE_AUTO'
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 416, in <module>
    elif mode==1: captura(name,url)
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 258, in captura
    comecarvideo(name,streamurl)
  File "/var/mobile/Containers/Data/Application/D7A5F859-5769-44C9-94B7-F6EDE0D38476/Library/Caches/home/addons/plugin.video.tvgolo/default.py", line 340, in comecarvideo
    xbmcPlayer = xbmc.Player(xbmc.PLAYER_CORE_AUTO)
AttributeError: 'module' object has no attribute 'PLAYER_CORE_AUTO'
-->End of Python script error report<--
</pre>

Se conseguires testar com o Kodi v17 acho que consegues ver logo o problema.

**Comment by fightnight** [comment]
Addon actualizado para v1.0.5  Testem lá agora.

**Comment by joaomvfsantos** [comment]
@fightnight Já funciona, perfeito. Por mim podes fechar o issue.
